export const LANGUAGES = {
  javascript: {
    name: "JavaScript",
    shikiId: "javascript",
    hljsId: "javascript",
    aliases: ["js", "jsx"],
    src: () => import("shiki/langs/javascript.mjs"),
  },
  typescript: {
    name: "TypeScript",
    shikiId: "typescript",
    hljsId: "typescript",
    aliases: ["ts", "tsx"],
    src: () => import("shiki/langs/typescript.mjs"),
  },
  python: {
    name: "Python",
    shikiId: "python",
    hljsId: "python",
    aliases: ["py"],
    src: () => import("shiki/langs/python.mjs"),
  },
  go: {
    name: "Go",
    shikiId: "go",
    hljsId: "go",
    aliases: [],
    src: () => import("shiki/langs/go.mjs"),
  },
  rust: {
    name: "Rust",
    shikiId: "rust",
    hljsId: "rust",
    aliases: ["rs"],
    src: () => import("shiki/langs/rust.mjs"),
  },
  java: {
    name: "Java",
    shikiId: "java",
    hljsId: "java",
    aliases: [],
    src: () => import("shiki/langs/java.mjs"),
  },
  ruby: {
    name: "Ruby",
    shikiId: "ruby",
    hljsId: "ruby",
    aliases: ["rb"],
    src: () => import("shiki/langs/ruby.mjs"),
  },
  php: {
    name: "PHP",
    shikiId: "php",
    hljsId: "php",
    aliases: [],
    src: () => import("shiki/langs/php.mjs"),
  },
  sql: {
    name: "SQL",
    shikiId: "sql",
    hljsId: "sql",
    aliases: [],
    src: () => import("shiki/langs/sql.mjs"),
  },
  bash: {
    name: "Bash",
    shikiId: "bash",
    hljsId: "bash",
    aliases: ["sh", "shell", "zsh"],
    src: () => import("shiki/langs/bash.mjs"),
  },
  html: {
    name: "HTML",
    shikiId: "html",
    hljsId: "xml",
    aliases: [],
    src: () => import("shiki/langs/html.mjs"),
  },
  css: {
    name: "CSS",
    shikiId: "css",
    hljsId: "css",
    aliases: ["scss", "less"],
    src: () => import("shiki/langs/css.mjs"),
  },
  json: {
    name: "JSON",
    shikiId: "json",
    hljsId: "json",
    aliases: [],
    src: () => import("shiki/langs/json.mjs"),
  },
  yaml: {
    name: "YAML",
    shikiId: "yaml",
    hljsId: "yaml",
    aliases: ["yml"],
    src: () => import("shiki/langs/yaml.mjs"),
  },
  markdown: {
    name: "Markdown",
    shikiId: "markdown",
    hljsId: "markdown",
    aliases: ["md"],
    src: () => import("shiki/langs/markdown.mjs"),
  },
  c: {
    name: "C",
    shikiId: "c",
    hljsId: "c",
    aliases: [],
    src: () => import("shiki/langs/c.mjs"),
  },
  cpp: {
    name: "C++",
    shikiId: "cpp",
    hljsId: "cpp",
    aliases: ["c++"],
    src: () => import("shiki/langs/cpp.mjs"),
  },
  csharp: {
    name: "C#",
    shikiId: "csharp",
    hljsId: "csharp",
    aliases: ["cs", "c#"],
    src: () => import("shiki/langs/csharp.mjs"),
  },
  swift: {
    name: "Swift",
    shikiId: "swift",
    hljsId: "swift",
    aliases: [],
    src: () => import("shiki/langs/swift.mjs"),
  },
  kotlin: {
    name: "Kotlin",
    shikiId: "kotlin",
    hljsId: "kotlin",
    aliases: ["kt"],
    src: () => import("shiki/langs/kotlin.mjs"),
  },
  dart: {
    name: "Dart",
    shikiId: "dart",
    hljsId: "dart",
    aliases: [],
    src: () => import("shiki/langs/dart.mjs"),
  },
} as const;

export type LanguageKey = keyof typeof LANGUAGES;

export const LANGUAGE_OPTIONS = [
  { value: "auto", label: "Auto-detect" },
  { value: "javascript", label: "JavaScript" },
  { value: "typescript", label: "TypeScript" },
  { value: "python", label: "Python" },
  { value: "go", label: "Go" },
  { value: "rust", label: "Rust" },
  { value: "java", label: "Java" },
  { value: "ruby", label: "Ruby" },
  { value: "php", label: "PHP" },
  { value: "sql", label: "SQL" },
  { value: "bash", label: "Bash" },
  { value: "html", label: "HTML" },
  { value: "css", label: "CSS" },
  { value: "json", label: "JSON" },
  { value: "yaml", label: "YAML" },
  { value: "markdown", label: "Markdown" },
  { value: "c", label: "C" },
  { value: "cpp", label: "C++" },
  { value: "csharp", label: "C#" },
  { value: "swift", label: "Swift" },
  { value: "kotlin", label: "Kotlin" },
  { value: "dart", label: "Dart" },
];

export const TIER_1_LANGUAGES = ["javascript", "typescript"] as const;
export const TIER_2_LANGUAGES = Object.keys(LANGUAGES).filter(
  (lang) => !TIER_1_LANGUAGES.includes(lang as typeof TIER_1_LANGUAGES[number])
) as readonly LanguageKey[];
