import { faker } from "@faker-js/faker"
import { db } from "./src/db"
import { roasts, analysisItems } from "./src/db/schema"

const LANGUAGES = [
  "javascript",
  "typescript",
  "python",
  "java",
  "go",
  "rust",
  "c",
  "cpp",
  "csharp",
  "ruby",
  "php",
  "swift",
  "kotlin",
  "sql",
] as const

const VERDICTS = [
  "needs_serious_help",
  "rough_around_edges",
  "decent_code",
  "solid_work",
  "exceptional",
] as const

const SEVERITIES = ["critical", "warning", "good"] as const

const ROAST_QUOTES = [
  "This code is so bad, even your compiler is crying.",
  "I've seen better code in a Hello World tutorial.",
  "Your code is like a onion - it has layers and makes people cry.",
  "This is why we can't have nice things.",
  "Sir, this is a Wendy's - not a place for this code.",
  "The documentation must be in another castle.",
  "This code was written during a full moon.",
  "Are you trying to summon Cthulhu? Because this code is eldritch.",
  "I've seen less errors in a horoscope.",
  "Your variable names are more confusing than the plot of Inception.",
  "This code is a masterpiece of chaos theory.",
  "The person who wrote this should be studied... for cautionary purposes.",
  "Is this a code or a crime scene?",
  "This would fail even the most lenient code review.",
  "I've seen better logic in a Magic 8 Ball.",
  "Your code has more bugs than a summer picnic.",
  "This is the programming equivalent of finger painting.",
  "The indentation is giving me schizophrenia.",
  "This code was generated by an AI having a nightmare.",
  "Congratulations, you invented technical debt.",
]

const CODE_EXAMPLES: Record<string, string[]> = {
  javascript: [
    `var x = 1;
var y = 2;
var z = x + y;
console.log(z);`,
    `if (x == true) {
  return true;
} else if (x == false) {
  return false;
} else {
  return !false;
}`,
    `function sum(a,b) { return a+b }`,
    `const arr = [1,2,3];
for(var i=0; i<arr.length; i++) {
  console.log(arr[i]);
}`,
  ],
  python: [
    `x = 1
y = 2
z = x + y
print z`,
    `if x == True:
    return True
elif x == False:
    return False
else:
    return not False`,
    `def sum(a,b):
  return a+b`,
  ],
  typescript: [
    `const x: any = "1";
const y: number = 2;
const z = x + y;`,
    `interface Foo { bar: string }
const foo: Foo = {};`,
    `function add(a: number, b: number): number {
  return a + b;
}`,
  ],
  java: [
    `public class Main {
  public static void main(String[] args) {
    System.out.println("Hello World");
  }
}`,
    `int x = 1;
int y = 2;
int z = x + y;`,
  ],
  sql: [
    `SELECT * FROM users WHERE 1=1`,
    `SELECT * FROM users WHERE id = 1 OR 1=1`,
    `SELECT * FROM users WHERE name = 'admin' -- comment`,
  ],
}

const ANALYSIS_TITLES = {
  critical: [
    "Using deprecated var keyword",
    "No type safety",
    "SQL injection vulnerability",
    "Using eval()",
    "Global variable pollution",
    "No error handling",
    "Memory leak potential",
    "Synchronous blocking code",
  ],
  warning: [
    "Inefficient loop",
    "Magic numbers",
    "Missing error handling",
    "Inconsistent naming",
    "Code duplication",
    "Missing comments",
    "Too many nested levels",
    "Unused variables",
  ],
  good: [
    "Good variable naming",
    "Proper error handling",
    "Clean structure",
    "Efficient algorithm",
    "Modern syntax",
    "Type safety",
  ],
}

const ANALYSIS_DESCRIPTIONS: Record<string, string[]> = {
  critical: [
    "The var keyword is function-scoped rather than block-scoped, which can lead to unexpected behavior.",
    "Using 'any' defeats the purpose of TypeScript's type system.",
    "This query is vulnerable to SQL injection attacks.",
    "Using eval() is extremely dangerous and should be avoided.",
    "Global variables can cause hard-to-debug issues.",
  ],
  warning: [
    "This loop could be optimized using built-in methods like map, filter, or reduce.",
    "Magic numbers make code hard to maintain. Consider using named constants.",
    "This function could throw errors that aren't being handled.",
    "Consider using a more descriptive variable name.",
    "This code appears in multiple places. Consider extracting to a function.",
  ],
  good: [
    "Variable names are clear and descriptive.",
    "Proper try-catch blocks for error handling.",
    "Code structure is clean and easy to follow.",
    "Efficient use of modern language features.",
  ],
}

function getVerdict(score: number): (typeof VERDICTS)[number] {
  if (score <= 2) return "needs_serious_help"
  if (score <= 4) return "rough_around_edges"
  if (score <= 6) return "decent_code"
  if (score <= 8) return "solid_work"
  return "exceptional"
}

function getRandomElement<T>(arr: readonly T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]
}

function generateCode(language: string): string {
  const examples = CODE_EXAMPLES[language] || CODE_EXAMPLES.javascript
  return getRandomElement(examples)
}

function generateRoastQuote(): string | undefined {
  if (Math.random() > 0.7) {
    return getRandomElement(ROAST_QUOTES)
  }
  return undefined
}

function generateAnalysisItems(roastId: string, score: number) {
  const items = []
  const count = faker.number.int({ min: 1, max: 5 })

  let severityPool: (typeof SEVERITIES)[number][]

  if (score <= 3) {
    severityPool = ["critical", "critical", "warning"]
  } else if (score <= 6) {
    severityPool = ["warning", "warning", "good"]
  } else {
    severityPool = ["good", "good", "good"]
  }

  for (let i = 0; i < count; i++) {
    const severity = getRandomElement(severityPool)
    items.push({
      id: faker.string.uuid(),
      roastId,
      severity,
      title: getRandomElement(ANALYSIS_TITLES[severity]),
      description: getRandomElement(ANALYSIS_DESCRIPTIONS[severity]),
      order: i,
    })
  }

  return items
}

async function seed() {
  console.log("🌱 Starting seed...")

  const roastRecords = []

  for (let i = 0; i < 100; i++) {
    const language = getRandomElement(LANGUAGES)
    const score = faker.number.float({ min: 0, max: 10, fractionDigits: 1 })
    const verdict = getVerdict(score)
    const roastMode = faker.datatype.boolean()
    const code = generateCode(language)
    const lineCount = code.split("\n").length
    const roastQuote = generateRoastQuote()

    const roast = {
      id: faker.string.uuid(),
      code,
      language,
      lineCount,
      roastMode,
      score,
      verdict,
      roastQuote,
      suggestedFix: score < 5 ? code.replace(/var/g, "const") : undefined,
      createdAt: faker.date.past({ years: 1 }),
    }

    roastRecords.push(roast)
  }

  console.log(`📝 Inserting ${roastRecords.length} roasts...`)

  await db.insert(roasts).values(roastRecords)

  const allRoasts = await db.select().from(roasts)

  console.log(`📝 Inserting analysis items...`)

  const analysisRecords = []

  for (const roast of allRoasts) {
    const items = generateAnalysisItems(roast.id, roast.score)
    analysisRecords.push(...items)
  }

  await db.insert(analysisItems).values(analysisRecords)

  console.log(`✅ Seed completed!`)
  console.log(`   - ${allRoasts.length} roasts`)
  console.log(`   - ${analysisRecords.length} analysis items`)
}

seed()
  .catch((e) => {
    console.error("❌ Seed failed:", e)
    process.exit(1)
  })
  .finally(() => {
    process.exit(0)
  })
